apiVersion: "batch/v2alpha1"
kind: CronJob
metadata:
  name: nexus-cleaner
  namespace: sdlc
spec:
  schedule: "0 20 * * *"
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 7
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: nexus-cleaner
          containers:
            - name: nexus-cleaner
              image: darumatic/nexus-cleaner:3.0
              env:
              - name: KEEP_LIMIT
                value: "300"
              - name: DOCKER_REGISTRY
                value: "localhost:5000"
              volumeMounts:
              - name: secret-volume
                mountPath: /nexus/secret
          volumes:
          - name: secret-volume
            secret:
              secretName: nexus-cleaner
          restartPolicy: OnFailure
