apiVersion: "batch/v2alpha1"
kind: CronJob
metadata:
  name: nexus-cleaner
  namespace: sdlc
spec:
  schedule: "*/1 * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: nexus-cleaner
          containers:
            - name: nexus-cleaner
              image: darumatic/nexus-cleaner:latest
              env:
              - name: KEEP_LIMIT
                value: "800"
              - name: DOCKER_REGISTRY
                value: "localhost:1234"
              volumeMounts:
              - name: secret-volume
                mountPath: /nexus/secret
          volumes:
          - name: secret-volume
            secret:
              secretName: nexus-cleaner
          restartPolicy: OnFailure
