kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nexus-cleaner
subjects:
- kind: ServiceAccount
  name: nexus-cleaner
  namespace: sdlc
roleRef:
  kind: ClusterRole
  name: list-pods
  apiGroup: rbac.authorization.k8s.io